name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: actions/subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0'

      - name: Get Dependencies
        run: flutter pub get

      - name: Create Android Build Skeleton
        run: flutter create . --platforms=android

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: galaxia-mind-apk
          path: build/app/outputs/flutter-apk/app-release.apk
